apiVersion: veecode.backstage.io/v1alpha1
kind: Cluster
metadata:
  name: "cluster-teste-3"
  environment:
    cluster_type: ec2
    domain: vkpr.platform.vee.codes
    ingress_type: kong
    certificate_account_email: platformss@vee.codes
    certificate_environment_type: staging
    grafana_obs_api:
    public_ip: 34.206.222.2
  annotations:
    backstage.io/kubernetes-id: "cluster-teste-3"
    github.com/project-slug: veecode-homolog/cluster-teste-3
    infracost/project: cluster-teste-3
    backstage.io/techdocs-ref: dir:..
    github.com/workflows: terraform-deploy.yml,start-instance.yml,stop-instance.yml,kubeconfig.yml,terraform-destroy.yml,infracost.yml
    cluster/instructions: "# Run the following commands to import the kubeconfig:\n  ssh -i ./cert.pem -o StrictHostKeyChecking=no $USERNAME@$34.206.222.2 \"mkdir -p .kube && k3d kubeconfig get k3s > ~/.kube/config\"\n  scp -i ./cert.pem $USERNAME@$34.206.222.2:~/.kube/config ~/.kube/config-cluster-teste-3\n  yq -e 'del(.clusters[0].cluster.certificate-authority-data) | .clusters[0].cluster.insecure-skip-tls-verify=true | .clusters[].cluster.server |= sub(\"0.0.0.0\", \"34.206.222.2\")' -i ~/.kube/config-cluster-teste-3\n  export KUBECONFIG=~/.kube/config-cluster-teste-3\n  kubectl get pods -A\n"
    veecode/cluster-name: cluster-teste-3
    kubernetes.io/secret-name: cluster-teste-3-secret
    kubernetes.io/secret-namespace: veecode-homolog
    kubernetes.io/auth-provider: custom
    kubernetes.io/api-server: https://34.206.222.2:6550
    kubernetes.io/skip-tls-verify: "true"
    kubernetes.io/skip-metrics-lookup: "false"
spec:
  type: ec2
  lifecycle: experimental
  owner: "group:default/admin"
  environment: 'environment:default/platform_homolog_environment'
